name: qscan
version: "1.0"
author: stackboom <artisancode@163.cn>
about: A simple program for find computer info.
args:
    - port:
        short: p
        long: port
        value_name: FILE
        help: Query port
        takes_value: true
    - INPUT:
        help: Sets the input file to use
        required: true
        index: 1
    - verbose:
        short: v
        multiple: true
        help: Sets the level of verbosity
subcommands:
    - test:
        about: controls testing features
        version: "1.3"
        author: Someone E. <someone_else@other.com>
        args:
            - debug:
                short: d
                help: print debug information
